<?php

namespace AppBundle\Repository;

/**
 * todoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class todoListRepository extends \Doctrine\ORM\EntityRepository
{
}
